"""JSON Schema definitions for daily ingest pipeline."""
from __future__ import annotations

CANDIDATE_SCHEMA = {
    "type": "object",
    "required": ["provisional_id", "doi", "title_en", "first_author", "year"],
    "properties": {
        "provisional_id": {"type": "string"},
        "recommendation": {"type": "string"},
        "doi": {"type": "string"},
        "title_en": {"type": "string"},
        "title_zh": {"type": "string"},
        "first_author": {"type": "string"},
        "authors": {"type": "string"},
        "year": {"type": "string"},
        "journal": {"type": "string"},
        "volume": {"type": "string"},
        "issue": {"type": "string"},
        "pages_or_article": {"type": "string"},
        "official_url": {"type": "string"},
        "document_type": {"type": "string"},
        "study_area": {"type": "string"},
        "research_object": {"type": "string"},
        "methods": {"type": "string"},
        "findings": {"type": "string"},
        "innovation": {"type": "string"},
        "limitations": {"type": "string"},
        "relevance": {"type": "string"},
        "suggested_chapter": {"type": "string"},
        "tags": {"type": "string"},
        "reading_priority": {"type": "string"},
        "verification_status": {"type": "string"},
        "ris": {"type": "string"},
        "bibtex": {"type": "string"},
    },
}

PREFLIGHT_SUMMARY_SCHEMA = {
    "type": "object",
    "required": ["status", "action", "master_count_before", "last_id_before", "candidate_count"],
    "properties": {
        "status": {"type": "string", "enum": ["pass", "blocked"]},
        "action": {"type": "string", "enum": ["no_update", "duplicate_only", "manual_review_required", "apply", "blocked"]},
        "master_count_before": {"type": "integer"},
        "last_id_before": {"type": "string"},
        "candidate_count": {"type": "integer"},
        "new_count": {"type": "integer"},
        "duplicate_count": {"type": "integer"},
        "manual_review_count": {"type": "integer"},
        "proposed_final_ids": {"type": "array", "items": {"type": "string"}},
        "errors": {"type": "array", "items": {"type": "string"}},
        "warnings": {"type": "array", "items": {"type": "string"}},
    },
}

RUN_SUMMARY_SCHEMA = {
    "type": "object",
    "required": ["status", "action", "master_count_before", "master_count_after"],
    "properties": {
        "status": {"type": "string", "enum": ["success", "failed"]},
        "action": {"type": "string"},
        "master_count_before": {"type": "integer"},
        "master_count_after": {"type": "integer"},
        "last_id_before": {"type": "string"},
        "last_id_after": {"type": "string"},
        "candidate_count": {"type": "integer"},
        "added_count": {"type": "integer"},
        "duplicate_count": {"type": "integer"},
        "manual_review_count": {"type": "integer"},
        "id_continuous": {"type": "boolean"},
        "doi_duplicates": {"type": "integer"},
        "english_title_duplicates": {"type": "integer"},
        "chinese_title_duplicates": {"type": "integer"},
        "index_matches_workbook": {"type": "boolean"},
        "protected_paths_modified": {"type": "boolean"},
        "errors": {"type": "array", "items": {"type": "string"}},
        "warnings": {"type": "array", "items": {"type": "string"}},
    },
}
